#!/bin/zsh

echo "----------"
echo "./main -a -p abc"
./main -a -p abc

echo "----------"
echo "./main -p abc"
./main -p abc

echo "----------"
echo "./main -p"
./main -p

echo "----------"
echo "./main -p -a"
./main -p -a

echo "----------"
echo "./main -a"
./main -a

echo "----------"
echo "./main -p abc def"
./main -p abc def